wandb_version: 1

path_exp_dir:
  desc: null
  value: exps/test
gpu_ids:
  desc: null
  value:
  - 0
path_load_dataset:
  desc: null
  value: data/all_data
num_epochs:
  desc: null
  value: 100000
batch_size:
  desc: null
  value: 7
eval_batch_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 2.0e-05
criterion:
  desc: null
  value: MSELoss()
interval_val:
  desc: null
  value: 1
seed:
  desc: null
  value: 0
debugging:
  desc: null
  value: false
interval_checkpoint:
  desc: null
  value: null
epoch_checkpoint:
  desc: null
  value: 20
run_name:
  desc: null
  value: DeBData
id:
  desc: null
  value: null
tags:
  desc: null
  value: []
nn_module:
  desc: null
  value: RepMode
adopted_datasets:
  desc: null
  value:
  - Normal
path_load_model:
  desc: null
  value: null
monitor_model:
  desc: null
  value: false
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.9.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700327336.944969
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      3:
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.15.12
      8:
      - 3
      - 8
      13: windows-amd64
